### ISSUE TITLE
Hey! Im running my code and i get this error.

### ISSUE THREAD

**Issue by whenthesuspicious** [Zacky2613/Python-Kahoot-Bot#2]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/104165130/164531387-06e74cb8-a036-4b81-8d37-516115f567da.png">
Can you please fix it?
line:     game_pin = int(room_key_entry.get())

**Comment by Zacky2613** [comment]
Thank you @whenthesuspicious,

Good News:  I have gone ahead and fixed the bug! I'm sorry for any problems this might have caused 

Bad News: I have found out through testing that it now appears to no longer work, when trying to join a kahoot game the bots will not appear on the screen where people's username pop out, however when trying to use the name it says it's taken. If you can get it to work for you then please contact me through twitter @ zacky2613 but until then I'll archive it

**Comment by whenthesuspicious** [comment]
Hello. Thanks for reaching out to me.
I will try to fix this issue as I do know some python.
I will get back to you with a solution.
Thanks!
